import React, { useState, useEffect, useMemo } from "react";
import { Search, Download, Trash2, Eye, Calendar, X } from "lucide-react";
import { ref as dbRef, onValue, remove } from "firebase/database";
import { db } from "../services/firebase";
import { createAuditLogger } from "../utils/AuditLogger";

const ReportHistory = ({ currentUser }) => {
  const [reports, setReports] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [filterType, setFilterType] = useState("All");
  const [loading, setLoading] = useState(true);
  const [selectedReport, setSelectedReport] = useState(null);

  const actorId = currentUser?.uid || currentUser?.id || "unknown";
  const actorLabel =
    currentUser?.actorLabel ||
    currentUser?.displayName ||
    currentUser?.email ||
    "Unknown";
  const auditLogger = useMemo(
    () =>
      createAuditLogger(actorId, actorLabel, currentUser?.role || "Unknown"),
    [actorId, actorLabel, currentUser?.role]
  );

  useEffect(() => {
    const reportsRef = dbRef(db, "reports");
    const unsubscribe = onValue(
      reportsRef,
      (snapshot) => {
        if (snapshot.exists()) {
          const reportsData = snapshot.val();
          const reportsList = Object.entries(reportsData).map(
            ([key, value]) => ({
              id: key,
              ...value,
              status: "Complete",
            })
          );
          setReports(reportsList.reverse()); // Most recent first
        } else {
          setReports([]);
        }
        setLoading(false);
      },
      (error) => {
        console.error("Error fetching reports:", error);
        setLoading(false);
      }
    );

    return () => unsubscribe();
  }, []);

  const filteredReports = reports.filter((report) => {
    const matchesSearch =
      report.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
      (report.generatedBy &&
        report.generatedBy.toLowerCase().includes(searchTerm.toLowerCase()));
    const matchesType = filterType === "All" || report.type === filterType;
    return matchesSearch && matchesType;
  });

  const handleDelete = async (id) => {
    if (window.confirm("Are you sure you want to delete this report?")) {
      try {
        const reportRef = dbRef(db, `reports/${id}`);
        const target = reports.find((report) => report.id === id) || null;
        await remove(reportRef);
        setReports(reports.filter((r) => r.id !== id));
        if (auditLogger?.logAction) {
          await auditLogger.logAction("DELETE", "Reports", {
            recordId: id,
            recordName: target?.name,
            reportType: target?.type,
          });
        }
        alert("✅ Report deleted successfully!");
      } catch (error) {
        console.error("Error deleting report:", error);
        alert("❌ Error deleting report");
      }
    }
  };

  const handleDownload = async (report) => {
    try {
      // Create CSV data
      const csvHeaders = [
        "Report Name",
        "Type",
        "Date Range",
        "Generated By",
        "Generated Date",
        "Status",
        "Total Members",
        "Total Revenue",
        "Total Benefits",
      ];

      const csvRow = [
        report.name || "Untitled Report",
        report.type || "N/A",
        report.dateRange || "N/A",
        report.generatedBy || "System",
        report.generatedDate
          ? new Date(report.generatedDate).toLocaleString()
          : "N/A",
        report.status || "Complete",
        report.totalMembers || 0,
        report.totalRevenue || 0,
        report.totalBenefits || 0,
      ];

      // Create CSV content
      const csvContent = [
        csvHeaders.join(","),
        csvRow.map((cell) => `"${cell}"`).join(","),
      ].join("\n");

      // Create blob and download
      const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
      const link = document.createElement("a");
      link.href = URL.createObjectURL(blob);
      link.download = `${report.name}.csv`;
      link.click();
      alert("✅ Report exported to Excel!");

      if (auditLogger?.logReportExported) {
        await auditLogger.logReportExported(
          report.id || `history-${Date.now()}`,
          report.type || "Unknown",
          "CSV"
        );
      }
    } catch (error) {
      console.error("Error downloading report:", error);
      alert("❌ Error exporting report");
    }
  };

  const handleView = (report) => {
    setSelectedReport(report);
  };

  return (
    <div className="space-y-6">
      {/* Search and Filters */}
      <div className="bg-white rounded-2xl shadow-lg p-6">
        <div className="flex flex-wrap gap-4 items-center">
          <div className="flex-1 min-w-[300px] relative">
            <Search className="w-5 h-5 text-gray-400 absolute left-4 top-1/2 transform -translate-y-1/2" />
            <input
              type="text"
              placeholder="Search Reports..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full border-2 border-gray-200 rounded-xl px-12 py-3 focus:outline-none focus:border-purple-500"
            />
          </div>
          <select
            value={filterType}
            onChange={(e) => setFilterType(e.target.value)}
            className="border-2 border-gray-200 rounded-xl px-4 py-3 focus:outline-none focus:border-purple-500 bg-white"
          >
            <option value="All">All Types</option>
            <option value="membership">Membership</option>
            <option value="financial">Financial</option>
            <option value="benefits">Services</option>
            <option value="demographic">Demographic</option>
          </select>
        </div>
      </div>

      {/* Reports Table */}
      <div className="bg-white rounded-2xl shadow-xl overflow-hidden">
        {loading ? (
          <div className="flex justify-center items-center py-12">
            <div className="text-gray-500">Loading reports...</div>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gradient-to-r from-purple-600 to-purple-700">
                <tr>
                  {[
                    "Report Name",
                    "Type",
                    "Date Range",
                    "Generated By",
                    "Generated Date",
                    "Status",
                    "Actions",
                  ].map((header) => (
                    <th
                      key={header}
                      className="px-6 py-4 text-left text-sm font-semibold text-white"
                    >
                      {header}
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {filteredReports.length > 0 ? (
                  filteredReports.map((report) => (
                    <tr
                      key={report.id}
                      className="hover:bg-gray-50 transition-colors"
                    >
                      <td className="px-6 py-4 text-sm font-semibold text-gray-900">
                        {report.name || "Untitled Report"}
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-700">
                        <span className="px-3 py-1 bg-purple-100 text-purple-700 rounded-full text-xs font-bold">
                          {report.type || "N/A"}
                        </span>
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-600">
                        {report.dateRange || "N/A"}
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-600">
                        {report.generatedBy || "System"}
                      </td>
                      <td className="px-6 py-4 text-sm text-gray-600">
                        {report.generatedDate
                          ? new Date(report.generatedDate).toLocaleString()
                          : "N/A"}
                      </td>
                      <td className="px-6 py-4 text-sm">
                        <span className="px-3 py-1 bg-green-100 text-green-700 rounded-full text-xs font-bold">
                          ✓ {report.status}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex gap-2">
                          <button
                            onClick={() => handleDownload(report)}
                            className="p-2 bg-blue-100 text-blue-600 rounded-lg hover:bg-blue-200 transition-all"
                            title="Download"
                          >
                            <Download className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => handleView(report)}
                            className="p-2 bg-green-100 text-green-600 rounded-lg hover:bg-green-200 transition-all"
                            title="View"
                          >
                            <Eye className="w-4 h-4" />
                          </button>
                          <button
                            onClick={() => handleDelete(report.id)}
                            className="p-2 bg-red-100 text-red-600 rounded-lg hover:bg-red-200 transition-all"
                            title="Delete"
                          >
                            <Trash2 className="w-4 h-4" />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan="7" className="text-center py-12">
                      <p className="text-gray-500">No reports found</p>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {/* Preview Modal */}
      {selectedReport && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex justify-center items-center z-50 p-4">
          <div className="bg-white rounded-2xl w-full max-w-2xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
            <div className="bg-gradient-to-r from-purple-600 to-purple-700 px-8 py-6 flex justify-between items-center">
              <h2 className="text-2xl font-bold text-white">Report Preview</h2>
              <button
                onClick={() => setSelectedReport(null)}
                className="text-white hover:bg-purple-800 p-2 rounded-lg transition-all"
              >
                <X className="w-6 h-6" />
              </button>
            </div>

            <div className="p-8 space-y-6 overflow-y-auto flex-1">
              <div className="grid grid-cols-2 gap-6">
                <div className="space-y-2">
                  <p className="text-xs font-semibold text-gray-500 uppercase">
                    Report Name
                  </p>
                  <p className="text-lg font-bold text-gray-900">
                    {selectedReport.name || "Untitled Report"}
                  </p>
                </div>
                <div className="space-y-2">
                  <p className="text-xs font-semibold text-gray-500 uppercase">
                    Report Type
                  </p>
                  <p className="inline-block px-3 py-1 bg-purple-100 text-purple-700 rounded-full text-sm font-bold">
                    {selectedReport.type || "N/A"}
                  </p>
                </div>
              </div>

              <div className="border-t-2 border-gray-100 pt-4">
                <div className="grid grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <p className="text-xs font-semibold text-gray-500 uppercase">
                      Date Range
                    </p>
                    <p className="text-sm text-gray-700">
                      {selectedReport.dateRange || "N/A"}
                    </p>
                  </div>
                  <div className="space-y-2">
                    <p className="text-xs font-semibold text-gray-500 uppercase">
                      Generated By
                    </p>
                    <p className="text-sm text-gray-700">
                      {selectedReport.generatedBy || "System"}
                    </p>
                  </div>
                </div>
              </div>

              <div className="border-t-2 border-gray-100 pt-4">
                <div className="grid grid-cols-2 gap-6">
                  <div className="space-y-2">
                    <p className="text-xs font-semibold text-gray-500 uppercase">
                      Generated Date
                    </p>
                    <p className="text-sm text-gray-700">
                      {selectedReport.generatedDate
                        ? new Date(
                            selectedReport.generatedDate
                          ).toLocaleString()
                        : "N/A"}
                    </p>
                  </div>
                  <div className="space-y-2">
                    <p className="text-xs font-semibold text-gray-500 uppercase">
                      Status
                    </p>
                    <p className="inline-block px-3 py-1 bg-green-100 text-green-700 rounded-full text-sm font-bold">
                      ✓ {selectedReport.status || "Complete"}
                    </p>
                  </div>
                </div>
              </div>

              <div className="border-t-2 border-gray-100 pt-4">
                <h3 className="text-sm font-bold text-gray-900 mb-4">
                  Report Summary
                </h3>
                <div className="grid grid-cols-3 gap-4">
                  <div className="bg-blue-50 p-4 rounded-xl">
                    <p className="text-xs font-semibold text-blue-600 uppercase">
                      Total Members
                    </p>
                    <p className="text-2xl font-bold text-blue-900 mt-2">
                      {selectedReport.totalMembers || 0}
                    </p>
                  </div>
                  <div className="bg-green-50 p-4 rounded-xl">
                    <p className="text-xs font-semibold text-green-600 uppercase">
                      Total Revenue
                    </p>
                    <p className="text-2xl font-bold text-green-900 mt-2">
                      ₱{(selectedReport.totalRevenue || 0).toLocaleString()}
                    </p>
                  </div>
                  <div className="bg-purple-50 p-4 rounded-xl">
                    <p className="text-xs font-semibold text-purple-600 uppercase">
                      Total Benefits
                    </p>
                    <p className="text-2xl font-bold text-purple-900 mt-2">
                      ₱{(selectedReport.totalBenefits || 0).toLocaleString()}
                    </p>
                  </div>
                </div>
              </div>

              {selectedReport.barangay && (
                <div className="border-t-2 border-gray-100 pt-4">
                  <p className="text-xs font-semibold text-gray-500 uppercase">
                    Filters Applied
                  </p>
                  <div className="mt-2 space-y-1 text-sm text-gray-700">
                    {selectedReport.barangay && (
                      <p>• Barangay: {selectedReport.barangay}</p>
                    )}
                    {selectedReport.ageGroup && (
                      <p>• Age Group: {selectedReport.ageGroup}</p>
                    )}
                    {selectedReport.status && (
                      <p>• Membership Status: {selectedReport.status}</p>
                    )}
                  </div>
                </div>
              )}
            </div>

            <div className="bg-gray-50 px-8 py-6 flex gap-4">
              <button
                onClick={() => handleDownload(selectedReport)}
                className="flex-1 px-6 py-3 bg-gradient-to-r from-green-600 to-green-700 text-white rounded-xl hover:from-green-700 hover:to-green-800 font-semibold flex items-center justify-center gap-2"
              >
                <Download className="w-5 h-5" />
                Export to Excel
              </button>
              <button
                onClick={() => setSelectedReport(null)}
                className="flex-1 px-6 py-3 bg-gray-200 text-gray-700 rounded-xl hover:bg-gray-300 font-semibold"
              >
                Close
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default ReportHistory;
